### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by sly-fox-git** [marcoluzi/obsidian-synthwave#1]
Please include how to install instructions in the Read Me file.

**Comment by marcoluzi** [comment]
@slyfoxgh Once my PR is merged this Theme will be displayed as an official Obsidian theme inside your Obsidian settings. If you want to use it earlier you can copy the obsidian.css inside your Obsidian theme folder.

`vault-folder/.obsidian/themes`

Rename the file to something else, like `SynthWave.css`. After that you can select the theme in your installed themes, inside your Obsidian appearance settings.

FYI: The theme is not yet optimised for Obsidian v.1.0.0. Will work on it as soon as possible.
